/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRAMES;

import SIMPLE_ADD.ADD_TEACHER;
import javax.swing.JOptionPane;

/**
 *
 * @author monica hancock
 */
public class DASHBOARD extends javax.swing.JFrame {

    /**
     * Creates new form DASHBOARD
     */
    public DASHBOARD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ADDTEACHERBUTTON = new javax.swing.JButton();
        ADDROOMBUTTON = new javax.swing.JButton();
        ADDSECTIONBUTTON = new javax.swing.JButton();
        ADDFACULTYBUTTON = new javax.swing.JButton();
        SETTINGBUTTON = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ADDROOMICON = new javax.swing.JLabel();
        ADDSECTIONICON = new javax.swing.JLabel();
        ADDFACULTYICON = new javax.swing.JLabel();
        SETTINGICON = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BACKGROUND = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DASHBOARD");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 33, -1, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial Narrow", 2, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/LOGOUT.png"))); // NOI18N
        jButton1.setText("LOG OUT");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 170, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 100));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ADDTEACHERBUTTON.setBackground(new java.awt.Color(0, 0, 102));
        ADDTEACHERBUTTON.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        ADDTEACHERBUTTON.setForeground(new java.awt.Color(255, 255, 0));
        ADDTEACHERBUTTON.setText("ADD TEACHER");
        ADDTEACHERBUTTON.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ADDTEACHERBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDTEACHERBUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(ADDTEACHERBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 190, 40));

        ADDROOMBUTTON.setBackground(new java.awt.Color(0, 0, 102));
        ADDROOMBUTTON.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        ADDROOMBUTTON.setForeground(new java.awt.Color(255, 255, 0));
        ADDROOMBUTTON.setText("ADD ROOM");
        ADDROOMBUTTON.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ADDROOMBUTTON.setMaximumSize(new java.awt.Dimension(191, 33));
        ADDROOMBUTTON.setMinimumSize(new java.awt.Dimension(191, 33));
        ADDROOMBUTTON.setPreferredSize(new java.awt.Dimension(191, 33));
        ADDROOMBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDROOMBUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(ADDROOMBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, 40));

        ADDSECTIONBUTTON.setBackground(new java.awt.Color(0, 0, 102));
        ADDSECTIONBUTTON.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        ADDSECTIONBUTTON.setForeground(new java.awt.Color(255, 255, 0));
        ADDSECTIONBUTTON.setText("ADD SECTION");
        ADDSECTIONBUTTON.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ADDSECTIONBUTTON.setMaximumSize(new java.awt.Dimension(191, 33));
        ADDSECTIONBUTTON.setMinimumSize(new java.awt.Dimension(191, 33));
        ADDSECTIONBUTTON.setPreferredSize(new java.awt.Dimension(191, 33));
        ADDSECTIONBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDSECTIONBUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(ADDSECTIONBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 190, 40));

        ADDFACULTYBUTTON.setBackground(new java.awt.Color(0, 0, 102));
        ADDFACULTYBUTTON.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        ADDFACULTYBUTTON.setForeground(new java.awt.Color(255, 255, 0));
        ADDFACULTYBUTTON.setText("ADD FACULTY");
        ADDFACULTYBUTTON.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ADDFACULTYBUTTON.setMaximumSize(new java.awt.Dimension(191, 33));
        ADDFACULTYBUTTON.setMinimumSize(new java.awt.Dimension(191, 33));
        ADDFACULTYBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDFACULTYBUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(ADDFACULTYBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 190, 40));

        SETTINGBUTTON.setBackground(new java.awt.Color(0, 0, 102));
        SETTINGBUTTON.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        SETTINGBUTTON.setForeground(new java.awt.Color(255, 255, 0));
        SETTINGBUTTON.setText("SETTING");
        SETTINGBUTTON.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SETTINGBUTTON.setMaximumSize(new java.awt.Dimension(191, 33));
        SETTINGBUTTON.setMinimumSize(new java.awt.Dimension(191, 33));
        SETTINGBUTTON.setPreferredSize(new java.awt.Dimension(191, 33));
        SETTINGBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SETTINGBUTTONActionPerformed(evt);
            }
        });
        jPanel2.add(SETTINGBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 210, 40));

        jLabel2.setBackground(new java.awt.Color(0, 51, 204));
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/user-20 - Copy.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 3));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 190, 160));

        ADDROOMICON.setBackground(new java.awt.Color(0, 51, 204));
        ADDROOMICON.setForeground(new java.awt.Color(0, 51, 204));
        ADDROOMICON.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ADDROOMICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/ADDROOM.png"))); // NOI18N
        ADDROOMICON.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));
        ADDROOMICON.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(ADDROOMICON, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 190, 160));

        ADDSECTIONICON.setBackground(new java.awt.Color(0, 51, 204));
        ADDSECTIONICON.setForeground(new java.awt.Color(0, 51, 204));
        ADDSECTIONICON.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ADDSECTIONICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/ADDSECTION.png"))); // NOI18N
        ADDSECTIONICON.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 3));
        ADDSECTIONICON.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(ADDSECTIONICON, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 190, 160));

        ADDFACULTYICON.setBackground(new java.awt.Color(0, 51, 204));
        ADDFACULTYICON.setForeground(new java.awt.Color(0, 51, 204));
        ADDFACULTYICON.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ADDFACULTYICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/ADDFACULTY.png"))); // NOI18N
        ADDFACULTYICON.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 3));
        jPanel2.add(ADDFACULTYICON, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 190, 160));

        SETTINGICON.setBackground(new java.awt.Color(0, 51, 204));
        SETTINGICON.setForeground(new java.awt.Color(0, 51, 204));
        SETTINGICON.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SETTINGICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/settings.png"))); // NOI18N
        SETTINGICON.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 3));
        jPanel2.add(SETTINGICON, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 210, 160));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/logog.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        BACKGROUND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/Presentation1.jpg"))); // NOI18N
        jPanel2.add(BACKGROUND, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 720));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 810, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 int choice=JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?",null,JOptionPane.OK_OPTION);
 if(choice == 0){
    new LOGIN_FRAME().setVisible(true);
    this.dispose();
 }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ADDTEACHERBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDTEACHERBUTTONActionPerformed
new ADDTEACHER().setVisible(true);
this.dispose();
    }//GEN-LAST:event_ADDTEACHERBUTTONActionPerformed

    private void ADDROOMBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDROOMBUTTONActionPerformed
      new ROOM().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_ADDROOMBUTTONActionPerformed

    private void ADDSECTIONBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDSECTIONBUTTONActionPerformed
  new ADDSECTION().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_ADDSECTIONBUTTONActionPerformed

    private void ADDFACULTYBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDFACULTYBUTTONActionPerformed
      new FACULTY().setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_ADDFACULTYBUTTONActionPerformed

    private void SETTINGBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SETTINGBUTTONActionPerformed
       new SETTING().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_SETTINGBUTTONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DASHBOARD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDFACULTYBUTTON;
    private javax.swing.JLabel ADDFACULTYICON;
    private javax.swing.JButton ADDROOMBUTTON;
    private javax.swing.JLabel ADDROOMICON;
    private javax.swing.JButton ADDSECTIONBUTTON;
    private javax.swing.JLabel ADDSECTIONICON;
    private javax.swing.JButton ADDTEACHERBUTTON;
    private javax.swing.JLabel BACKGROUND;
    private javax.swing.JButton SETTINGBUTTON;
    private javax.swing.JLabel SETTINGICON;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
