/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRAMES;

import FRAMES.PrintFrame.Faculty_Print;
import cs_system.DB_class.Add_Faculty;
import cs_system.DB_class.Add_Room;
import javax.swing.JOptionPane;

/**
 *
 * @author monica hancock
 */
public class FACULTY extends javax.swing.JFrame {

    String Days;
    String Start;
    String End;
    String Room;

    /**
     * Creates new form FACULTY
     */
    public FACULTY() {
        initComponents();
        Add_Faculty AF = new Add_Faculty();
        AF.DisplayData(jTable2);
        jButton5.setVisible(false);
        jButton2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BACKGROUNDFORADDTEACHER = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        SEARCHBUTTON = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        SECTION = new javax.swing.JTextField();
        COURSE_TITLE = new javax.swing.JTextField();
        DEPARTMENT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        DAY = new javax.swing.JComboBox<>();
        SCHED = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/FACULTYBACKGROUND.jpg"))); // NOI18N

        BACKGROUNDFORADDTEACHER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/BACKFORADDROOM.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 800));
        setMinimumSize(new java.awt.Dimension(1280, 800));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1280, 800));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 480, 50));

        SEARCHBUTTON.setBackground(new java.awt.Color(0, 0, 153));
        SEARCHBUTTON.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SEARCHBUTTON.setForeground(new java.awt.Color(255, 255, 255));
        SEARCHBUTTON.setText("SEARCH");
        SEARCHBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHBUTTONActionPerformed(evt);
            }
        });
        getContentPane().add(SEARCHBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, 160, 50));

        jScrollPane4.setBackground(new java.awt.Color(153, 204, 255));
        jScrollPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 204), 3));
        jScrollPane4.setForeground(new java.awt.Color(0, 0, 204));
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "SECTION", "COURSE TITLE", "DEPARTMENT", "DAYS", "START TIME", "END TIME", "ROOM"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setAutoscrolls(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable2);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 890, 540));

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(SECTION, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 270, 30));
        jPanel1.add(COURSE_TITLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 270, 30));
        jPanel1.add(DEPARTMENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 270, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("SECTION");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("COURSE TITLE");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("DEPARTMENT");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText("AVAILABLE SCHEDULE");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, 140, 30));

        DAY.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DAY", "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY", " " }));
        DAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DAYActionPerformed(evt);
            }
        });
        jPanel1.add(DAY, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 270, 30));

        jPanel1.add(SCHED, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 270, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("DAYS");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("ADD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 140, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("RESET");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 140, 30));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("UPDATE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 140, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 330, 530));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/exit-2.png"))); // NOI18N
        jButton1.setText("BACK");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, 50));

        jButton6.setText("EXPORT DATA");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/BACKFORADDTEACHER - Copy - Copy.jpg"))); // NOI18N
        jLabel3.setLabelFor(this);
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed

        
    }//GEN-LAST:event_searchActionPerformed

    private void SEARCHBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHBUTTONActionPerformed
Add_Faculty AF=new Add_Faculty();
if(AF.SearchData(search.getText().toUpperCase(), jTable2)==0){
    JOptionPane.showMessageDialog(this,"Cannot find data related to "+search.getText());
}
    }//GEN-LAST:event_SEARCHBUTTONActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Add_Faculty AF = new Add_Faculty();
       Add_Room AR = new Add_Room();
        String Check = Start + "-" + End + "-" + Room;
        AF.Splitter(SCHED.getSelectedItem().toString());
        
        if (Days.equals(DAY.getSelectedItem()) && SCHED.getSelectedItem().toString().contains(Check)) {
            int result = JOptionPane.showConfirmDialog(this, "This action cannot be undone.Are you sure you want to delete this schedule?", "Confirm Action", JOptionPane.OK_OPTION);
            if (result == 0) {
                String pass = JOptionPane.showInputDialog("Enter your password to confirm this action.");
                if (AR.ValidateDelete(pass)) {
                   
                    System.out.println(SCHED.getSelectedItem().toString().equalsIgnoreCase(Check));
                    System.out.println(SCHED.getSelectedItem().toString());
                     System.out.println(Check);
                    if (AF.DeleteData(DAY.getSelectedItem().toString()) == 1) {
                        
                        
                        
                        if (AF.UpdateIs_Used_Faculty(DAY.getSelectedItem().toString(), "false") == 1) {
                           
                            SECTION.setText("");
                            DEPARTMENT.setText("");
                            COURSE_TITLE.setText("");
                            DAY.setSelectedIndex(0);
                            SCHED.removeAllItems();
                            jButton5.setVisible(false);
                            jButton2.setVisible(false);
                            jButton3.setVisible(true);
                            JOptionPane.showMessageDialog(this, "Schedule was deleted successfully");
                            AF.DisplayData(jTable2);
                        }
                        else{
                           JOptionPane.showMessageDialog(this, "Error:Unknown error.Please contact support.1");  
                        }
                    }
                    else{
                          JOptionPane.showMessageDialog(this, "Error:Unknown error.Please contact support.2");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Wrong password.Please try again.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error:Schedule change cannot delete this data");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new DASHBOARD().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Add_Faculty AF = new Add_Faculty();
        if (SECTION.getText().isEmpty() || DEPARTMENT.getText().isEmpty() || COURSE_TITLE.getText().isEmpty() || DAY.getSelectedItem().toString().equals("DAY")) {
            JOptionPane.showMessageDialog(this, "Error:Empty feilds are not allowed.");
        } else {
            int action = JOptionPane.showConfirmDialog(this, "Are you sure you want to add this schedule for faculty?", "Confirm Action", JOptionPane.OK_OPTION);
            if (action == 0) {
                AF.Splitter(SCHED.getSelectedItem().toString());
                if (AF.Add_Data(SECTION.getText(), DEPARTMENT.getText(), DAY.getSelectedItem().toString(), COURSE_TITLE.getText()) == 1) {
                    if (AF.UpdateIs_Used_Faculty(DAY.getSelectedItem().toString(), "true") == 1) {
                        JOptionPane.showMessageDialog(this, "Faculty schedule added succesfully");
                        AF.DisplayData(jTable2);
                        SECTION.setText("");
                        DEPARTMENT.setText("");
                        COURSE_TITLE.setText("");
                        DAY.setSelectedIndex(0);
                        SCHED.removeAllItems();

                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Error:Cant add schedult.Please contact support.");
                }
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        SECTION.setText("");
        DEPARTMENT.setText("");
        COURSE_TITLE.setText("");
        DAY.setSelectedIndex(0);
        SCHED.removeAllItems();
        jButton5.setVisible(false);
        jButton2.setVisible(false);
        jButton3.setVisible(true);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Add_Faculty AF = new Add_Faculty();
        AF.Splitter(SCHED.getSelectedItem().toString());
        if (AF.Update_Data(SECTION.getText(), DEPARTMENT.getText(), DAY.getSelectedItem().toString(), COURSE_TITLE.getText(), Days, Start, End, Room) == 1) {
            String Check = Start + "-" + End + "-" + Room;
            if (!Days.equals(DAY.getSelectedItem()) || !Check.equals(SCHED.getSelectedItem().toString())) {
                if (AF.UpdateIs_Used_Faculty_Changed(Days, Start, End, Room, "false") == 1) {
                    if (AF.UpdateIs_Used_Faculty(DAY.getSelectedItem().toString(), "true") == 1) {
                        JOptionPane.showMessageDialog(this, "Schedule updated successfully");
                        SECTION.setText("");
                        DEPARTMENT.setText("");
                        COURSE_TITLE.setText("");
                        DAY.setSelectedIndex(0);
                        SCHED.removeAllItems();
                        jButton5.setVisible(false);
                        jButton2.setVisible(false);
                        jButton3.setVisible(true);
                        AF.DisplayData(jTable2);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Error:Unknown error occured.Please contact support.");
                }
            }

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void DAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DAYActionPerformed
        if (!DAY.getSelectedItem().toString().equals("DAY")) {
            Add_Faculty AF = new Add_Faculty();
            if (!AF.LoadScheds(SCHED, DAY.getSelectedItem().toString())) {

                JOptionPane.showMessageDialog(this, "No data on " + DAY.getSelectedItem().toString() + "\n Add data using Add Room button on dashboard");
            }
        }
    }//GEN-LAST:event_DAYActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        String Section = jTable2.getValueAt(jTable2.getSelectedRow(), 1).toString();
        String Course = jTable2.getValueAt(jTable2.getSelectedRow(), 2).toString();
        String Department = jTable2.getValueAt(jTable2.getSelectedRow(), 3).toString();
        Days = jTable2.getValueAt(jTable2.getSelectedRow(), 4).toString();
        Start = jTable2.getValueAt(jTable2.getSelectedRow(), 5).toString();
        End = jTable2.getValueAt(jTable2.getSelectedRow(), 6).toString();
        Room = jTable2.getValueAt(jTable2.getSelectedRow(), 7).toString();
        
        
        SECTION.setText(Section);
        COURSE_TITLE.setText(Course);
        DEPARTMENT.setText(Department);
        DAY.setSelectedItem(Days);
        SCHED.insertItemAt(Start + "-" + End + "-" + Room, 0);
        SCHED.setSelectedIndex(0);
        jButton3.setVisible(false);
        jButton5.setVisible(true);
        jButton2.setVisible(true);


    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
new Faculty_Print().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FACULTY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FACULTY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FACULTY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FACULTY.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FACULTY().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACKGROUNDFORADDTEACHER;
    private javax.swing.JTextField COURSE_TITLE;
    private javax.swing.JComboBox<String> DAY;
    private javax.swing.JTextField DEPARTMENT;
    private javax.swing.JComboBox<String> SCHED;
    private javax.swing.JButton SEARCHBUTTON;
    private javax.swing.JTextField SECTION;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField search;
    // End of variables declaration//GEN-END:variables
}
