/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SIMPLE_ADD;

import FRAMES.ADDTEACHER;
import FRAMES.DASHBOARD;
import SIMPLE_RECORD.CLASSES.Add_Teachers;
import SIMPLE_RECORD.CLASSES.FileCreator;
import SIMPLE_RECORD.CLASSES.ID_GENERATOR;
import SIMPLE_RECORD.CLASSES.Store_Selected;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class ADD_TEACHER extends javax.swing.JFrame {

    /**
     * Creates new form ADD_TEACHER
     */
    public ADD_TEACHER() {
        initComponents();

        Add_Teachers AT = new Add_Teachers();
        AT.DisplayData(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        FNAME = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MNAME = new javax.swing.JTextField();
        LNAME = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DPARTMENT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CLEAR = new javax.swing.JButton();
        ADDRECORD = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TEACHER NAME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(40);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 530, 560));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FNAME.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel2.add(FNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 272, 33));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("FIRST NAME");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("MIDDLE NAME");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        MNAME.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel2.add(MNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 272, 33));

        LNAME.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel2.add(LNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 272, 33));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("LAST NAME");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        DPARTMENT.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel2.add(DPARTMENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 272, 33));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("DEPARTMENT");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        CLEAR.setText("CLEAR");
        CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARActionPerformed(evt);
            }
        });
        jPanel2.add(CLEAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 150, 40));

        ADDRECORD.setText("ADD RECORD");
        ADDRECORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDRECORDActionPerformed(evt);
            }
        });
        jPanel2.add(ADDRECORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 150, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 390, 560));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/exit-2.png"))); // NOI18N
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 130, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/BACKFORADDROOM.jpg"))); // NOI18N
        jLabel1.setLabelFor(jPanel1);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new DASHBOARD().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ADDRECORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDRECORDActionPerformed
        ID_GENERATOR GEN = new ID_GENERATOR();
        String Generated = GEN.GenerateId();
        Add_Teachers AT = new Add_Teachers();

        int result = AT.AddTeacher(Generated, FNAME.getText().toUpperCase(), MNAME.getText().toUpperCase(), LNAME.getText().toUpperCase(), DPARTMENT.getText().toUpperCase());

        if (result == 1) {
            JOptionPane.showMessageDialog(this, "Teachers data has beed added");
        AT.DisplayData(jTable1);
        } else {
            JOptionPane.showMessageDialog(this, "Cannot add data for now.if problem continue please contact support.");
        }


    }//GEN-LAST:event_ADDRECORDActionPerformed

    private void CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARActionPerformed
        FNAME.setText(null);
        MNAME.setText(null);
        LNAME.setText(null);
        DPARTMENT.setText(null);

    }//GEN-LAST:event_CLEARActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        Store_Selected st = new Store_Selected();
        Add_Teachers AT = new Add_Teachers();
        int row = jTable1.getSelectedRow();
        String name = String.valueOf(jTable1.getValueAt(row, 1));
        String ID = AT.getID(name);

        if (ID.equals("")) {
            JOptionPane.showMessageDialog(this, "An error occured:Cannot fetch data from data base to procced.");
        } else {

            FileCreator fc = new FileCreator();
            if (fc.DirChecker()) {
                fc.CreateDir();
            }
            if (fc.CreateFile("Storage.ini")) {
                System.out.print("result");
            }
            try{
FileWriter fw =new FileWriter("C://cs_system/Storage.ini");
fw.write(name+","+ID);
fw.flush();
fw.close();
            }
            catch(Exception e){
                System.out.println(e);
            }
            
            new ADDTEACHER().setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADD_TEACHER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADD_TEACHER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADD_TEACHER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADD_TEACHER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADD_TEACHER().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDRECORD;
    private javax.swing.JButton CLEAR;
    private javax.swing.JTextField DPARTMENT;
    private javax.swing.JTextField FNAME;
    private javax.swing.JTextField LNAME;
    private javax.swing.JTextField MNAME;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
