/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRAMES.PrintFrame;

import cs_system.DB_class.Add_Teacher;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class Teacher_Print extends javax.swing.JFrame {

    /**
     * Creates new form Teacher_Print
     */
    public Teacher_Print() {
        initComponents();
        Add_Teacher AT = new Add_Teacher();
        if(jTable1.getRowCount()==0){
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/exit-2.png"))); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TEACHER NAME", "PROGRAM", "SECTION", "PSCS CODE", "COURSE TITLE", "DEPARTMENT", "S UNITS", "T UNITS", "CONTRACT HOURS", "DAYS", "START", "END", "ROOM", "REMARK"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 1120, 460));

        jButton2.setText("PRINT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 550, -1, -1));

        jButton3.setText("EXPORT AS CSV");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 550, -1, -1));

        jButton4.setText("Choose Teacher");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/BACKFORADDROOM.jpg"))); // NOI18N
        jLabel2.setLabelFor(jPanel1);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1183, 611));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            if (jTable1.print()) {
                JOptionPane.showMessageDialog(this, "Teacher schedule printed succesfully");
            } else {
                JOptionPane.showMessageDialog(this, "Print job canceled");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Add_Teacher AT = new Add_Teacher();
        JComboBox jcb = new JComboBox();
        AT.LoadTeacherList(jcb);
        JOptionPane.showMessageDialog(null, jcb, "select or type a value", JOptionPane.QUESTION_MESSAGE);
        AT.DisplayPrintData(jTable1, jcb.getSelectedItem().toString());
        jButton4.setText(jcb.getSelectedItem().toString());
        int SUNITS_TOTAL = 0;
        int TUNITS_TOTAL = 0;
        int CONTRACT_TOTAL = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            SUNITS_TOTAL = Integer.valueOf(jTable1.getValueAt(i, 7).toString()) + SUNITS_TOTAL;
            TUNITS_TOTAL = Integer.valueOf(jTable1.getValueAt(i, 8).toString()) + TUNITS_TOTAL;
            CONTRACT_TOTAL = Integer.valueOf(jTable1.getValueAt(i, 9).toString()) + CONTRACT_TOTAL;
        }
        DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
        dm.addRow(new Object[]{"", "", "", "", "", "", "Total:", SUNITS_TOTAL, TUNITS_TOTAL, CONTRACT_TOTAL, "", "", "", "", ""});
           jButton2.setEnabled(true);
            jButton3.setEnabled(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFileChooser jf = new JFileChooser();
        jf.setCurrentDirectory(new File(System.getProperty("user.home")));
        jf.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jf.setDialogTitle("Select directory to save file...");
        int action = jf.showOpenDialog(this);
        String filename = JOptionPane.showInputDialog("Enter your prefered filename... ");
        if (action == JFileChooser.APPROVE_OPTION) {
            if (filename.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Empty file name is not allowed.");
            } else {
                String path = jf.getSelectedFile().getAbsolutePath();
                File file = new File(path + "\\" + filename + ".csv");
                FileMaker fm = new FileMaker();
                if (fm.FileMake(path + "\\" + filename + ".csv") == 1) {
                    try {
                        FileWriter fr = new FileWriter(file, true);
                        fr.write(jTable1.getColumnName(1)
                                + "," + jTable1.getColumnName(2)
                                + "," + jTable1.getColumnName(3)
                                + "," + jTable1.getColumnName(4)
                                + "," + jTable1.getColumnName(5)
                                + "," + jTable1.getColumnName(6)
                                + "," + jTable1.getColumnName(7)
                                + "," + jTable1.getColumnName(8)
                                + "," + jTable1.getColumnName(9)
                                + "," + jTable1.getColumnName(10)
                                + "," + jTable1.getColumnName(11)
                                + "," + jTable1.getColumnName(12)
                                + "," + jTable1.getColumnName(13)
                                + "," + jTable1.getColumnName(14)
                                + "\n");
                        fr.flush();
                        for (int i = 0; i < jTable1.getRowCount(); i++) {
                            fr.write(jTable1.getValueAt(i, 1) + ","
                                    + jTable1.getValueAt(i, 2) + ","
                                    + jTable1.getValueAt(i, 3) + ","
                                    + jTable1.getValueAt(i, 4) + ","
                                    + jTable1.getValueAt(i, 5) + ","
                                    + jTable1.getValueAt(i, 6) + ","
                                    + jTable1.getValueAt(i, 7) + ","
                                    + jTable1.getValueAt(i, 8) + ","
                                    + jTable1.getValueAt(i, 9) + ","
                                    + jTable1.getValueAt(i, 10) + ","
                                    + jTable1.getValueAt(i, 11) + ","
                                    + jTable1.getValueAt(i, 12) + ","
                                    + jTable1.getValueAt(i, 13) + ","
                                    + jTable1.getValueAt(i, 14) + ","
                                    + "\n"
                            );
                            fr.flush();

                        }
                        JOptionPane.showMessageDialog(this, "Export finish you can find your file in :" + file);
                        fr.close();
                    } catch (IOException ex) {
                        Logger.getLogger(Teacher_Print.class.getName()).log(Level.SEVERE, null, ex);
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "File already exists");
                }

            }

        } else {
            JOptionPane.showMessageDialog(this, "Export aborted");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher_Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher_Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher_Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher_Print.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher_Print().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
